### ISSUE TITLE
Method _Init is missing in Node extern

### ISSUE THREAD

**Issue by NQNStudios** [HaxeGodot/godot#16]
Godot Nodes have an _init() function that is called before _ready(), and I need to override that. For some reason it's not in the haxe extern definition for Node. Here in the documentation for haxegodot you can also see that a reference to _Init is omitted: https://haxegodot.github.io/godot/godot/Node.html#_Ready

> Usually used for initialization. For even earlier initialization, may be used. See also [godot.Node._EnterTree](https://haxegodot.github.io/godot/godot/Node.html#_EnterTree).

It should say 

 > Usually used for initialization. For even earlier initialization, **godot.Node._Init** may be used. See also [godot.Node._EnterTree](https://haxegodot.github.io/godot/godot/Node.html#_EnterTree).

**Comment by NQNStudios** [comment]
I see this goes deeper to a bizarre issue in Godot C#... https://github.com/godotengine/godot/issues/32295

**Comment by ibilon** [comment]
If it's not available in the C# version of Godot it'll be complicated to make it work in the externs, and I agree that it wouldn't make sense to add it since it'll be the same as putting code in the constructor.
Godot's documentation could be more clear in the differences between gdscript and C#, but nothing that can be done here.
