### ISSUE TITLE
Wrong extern parameter types related to bytearrays

### ISSUE THREAD

**Issue by dazKind** [HaxeGodot/godot#5]
While working on procedural geometry I came across this issue. The `data` parameter's type in the following function should be `cs.NativeArray<cs.types.UInt8>`

https://github.com/HaxeGodot/godot/blob/227718e1ec5a902800b9ba2ecbf3078bf0ac3fff/godot/VisualServer.hx#L562

same for this one

https://github.com/HaxeGodot/godot/blob/227718e1ec5a902800b9ba2ecbf3078bf0ac3fff/godot/ArrayMesh.hx#L168

**Comment by ibilon** [comment]
The extern generator considered that if the last argument was an array it was a rest argument, which is false it seems.
Looking at the C# code from Godot, only the GD class use rest args.
I'll update the externs.

**Comment by ibilon** [comment]
Fixed by https://github.com/HaxeGodot/godot/commit/05e341e127659c0f0767e8c33ec11974d967acb9.
You can now pass an Array to it, though as with all functions that take an Array there can be a cost to make it into a NativeArray, if you'll keep changing it and sending it back to Godot I recommend you use a NativeArray directly.
